import pandas as pd

#df = pd.read_csv("test_lite.csv", sep = ';')
df0 = pd.read_csv("TEST 0.csv", sep = ';')
df1 = pd.read_csv("TEST 1.csv", sep = ';')
df2 = pd.read_csv("TEST 2.csv", sep = ';')
df3 = pd.read_csv("TEST 3.csv", sep = ';')
df4 = pd.read_csv("TEST 4.csv", sep = ';')
df5 = pd.read_csv("TRAIN 0.csv", sep = ';')
df6 = pd.read_csv("TRAIN 1.csv", sep = ';')
df7 = pd.read_csv("TRAIN 2.csv", sep = ';')
df8 = pd.read_csv("TRAIN 3.csv", sep = ';')
df9 = pd.read_csv("TRAIN 4.csv", sep = ';')
print(df0)   
print(df1)   
print(df2)   
print(df3)   
print(df4)   
print(df5)
print(df6)
print(df7)
print(df8)
print(df9)
